// Generated by gencpp from file bruce_msgs/GetOccupancyMapResponse.msg
// DO NOT EDIT!


#ifndef BRUCE_MSGS_MESSAGE_GETOCCUPANCYMAPRESPONSE_H
#define BRUCE_MSGS_MESSAGE_GETOCCUPANCYMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/OccupancyGrid.h>

namespace bruce_msgs
{
template <class ContainerAllocator>
struct GetOccupancyMapResponse_
{
  typedef GetOccupancyMapResponse_<ContainerAllocator> Type;

  GetOccupancyMapResponse_()
    : occ()  {
    }
  GetOccupancyMapResponse_(const ContainerAllocator& _alloc)
    : occ(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _occ_type;
  _occ_type occ;





  typedef boost::shared_ptr< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetOccupancyMapResponse_

typedef ::bruce_msgs::GetOccupancyMapResponse_<std::allocator<void> > GetOccupancyMapResponse;

typedef boost::shared_ptr< ::bruce_msgs::GetOccupancyMapResponse > GetOccupancyMapResponsePtr;
typedef boost::shared_ptr< ::bruce_msgs::GetOccupancyMapResponse const> GetOccupancyMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator1> & lhs, const ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.occ == rhs.occ;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator1> & lhs, const ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bruce_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f81179516ac8307b1a90ef4c8b13cd2b";
  }

  static const char* value(const ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf81179516ac8307bULL;
  static const uint64_t static_value2 = 0x1a90ef4c8b13cd2bULL;
};

template<class ContainerAllocator>
struct DataType< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bruce_msgs/GetOccupancyMapResponse";
  }

  static const char* value(const ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/OccupancyGrid occ\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/OccupancyGrid\n"
"# This represents a 2-D grid map, in which each cell represents the probability of\n"
"# occupancy.\n"
"\n"
"Header header \n"
"\n"
"#MetaData for the map\n"
"MapMetaData info\n"
"\n"
"# The map data, in row-major order, starting with (0,0).  Occupancy\n"
"# probabilities are in the range [0,100].  Unknown is -1.\n"
"int8[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/MapMetaData\n"
"# This hold basic information about the characterists of the OccupancyGrid\n"
"\n"
"# The time at which the map was loaded\n"
"time map_load_time\n"
"# The map resolution [m/cell]\n"
"float32 resolution\n"
"# Map width [cells]\n"
"uint32 width\n"
"# Map height [cells]\n"
"uint32 height\n"
"# The origin of the map [m, m, rad].  This is the real-world pose of the\n"
"# cell (0,0) in the map.\n"
"geometry_msgs/Pose origin\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.occ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetOccupancyMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bruce_msgs::GetOccupancyMapResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "occ: ";
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.occ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRUCE_MSGS_MESSAGE_GETOCCUPANCYMAPRESPONSE_H
