// Generated by gencpp from file bruce_msgs/GetOccupancyMap.msg
// DO NOT EDIT!


#ifndef BRUCE_MSGS_MESSAGE_GETOCCUPANCYMAP_H
#define BRUCE_MSGS_MESSAGE_GETOCCUPANCYMAP_H

#include <ros/service_traits.h>


#include <bruce_msgs/GetOccupancyMapRequest.h>
#include <bruce_msgs/GetOccupancyMapResponse.h>


namespace bruce_msgs
{

struct GetOccupancyMap
{

typedef GetOccupancyMapRequest Request;
typedef GetOccupancyMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetOccupancyMap
} // namespace bruce_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bruce_msgs::GetOccupancyMap > {
  static const char* value()
  {
    return "85f4445a9d44297d096f4d7339d7a4ce";
  }

  static const char* value(const ::bruce_msgs::GetOccupancyMap&) { return value(); }
};

template<>
struct DataType< ::bruce_msgs::GetOccupancyMap > {
  static const char* value()
  {
    return "bruce_msgs/GetOccupancyMap";
  }

  static const char* value(const ::bruce_msgs::GetOccupancyMap&) { return value(); }
};


// service_traits::MD5Sum< ::bruce_msgs::GetOccupancyMapRequest> should match
// service_traits::MD5Sum< ::bruce_msgs::GetOccupancyMap >
template<>
struct MD5Sum< ::bruce_msgs::GetOccupancyMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bruce_msgs::GetOccupancyMap >::value();
  }
  static const char* value(const ::bruce_msgs::GetOccupancyMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bruce_msgs::GetOccupancyMapRequest> should match
// service_traits::DataType< ::bruce_msgs::GetOccupancyMap >
template<>
struct DataType< ::bruce_msgs::GetOccupancyMapRequest>
{
  static const char* value()
  {
    return DataType< ::bruce_msgs::GetOccupancyMap >::value();
  }
  static const char* value(const ::bruce_msgs::GetOccupancyMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bruce_msgs::GetOccupancyMapResponse> should match
// service_traits::MD5Sum< ::bruce_msgs::GetOccupancyMap >
template<>
struct MD5Sum< ::bruce_msgs::GetOccupancyMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bruce_msgs::GetOccupancyMap >::value();
  }
  static const char* value(const ::bruce_msgs::GetOccupancyMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bruce_msgs::GetOccupancyMapResponse> should match
// service_traits::DataType< ::bruce_msgs::GetOccupancyMap >
template<>
struct DataType< ::bruce_msgs::GetOccupancyMapResponse>
{
  static const char* value()
  {
    return DataType< ::bruce_msgs::GetOccupancyMap >::value();
  }
  static const char* value(const ::bruce_msgs::GetOccupancyMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BRUCE_MSGS_MESSAGE_GETOCCUPANCYMAP_H
