// Generated by gencpp from file bruce_msgs/PredictSLAMUpdateResponse.msg
// DO NOT EDIT!


#ifndef BRUCE_MSGS_MESSAGE_PREDICTSLAMUPDATERESPONSE_H
#define BRUCE_MSGS_MESSAGE_PREDICTSLAMUPDATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <bruce_msgs/ISAM2Update.h>
#include <nav_msgs/Path.h>

namespace bruce_msgs
{
template <class ContainerAllocator>
struct PredictSLAMUpdateResponse_
{
  typedef PredictSLAMUpdateResponse_<ContainerAllocator> Type;

  PredictSLAMUpdateResponse_()
    : isam2_updates()
    , keyframes()  {
    }
  PredictSLAMUpdateResponse_(const ContainerAllocator& _alloc)
    : isam2_updates(_alloc)
    , keyframes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::bruce_msgs::ISAM2Update_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::bruce_msgs::ISAM2Update_<ContainerAllocator> >> _isam2_updates_type;
  _isam2_updates_type isam2_updates;

   typedef std::vector< ::nav_msgs::Path_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::nav_msgs::Path_<ContainerAllocator> >> _keyframes_type;
  _keyframes_type keyframes;





  typedef boost::shared_ptr< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PredictSLAMUpdateResponse_

typedef ::bruce_msgs::PredictSLAMUpdateResponse_<std::allocator<void> > PredictSLAMUpdateResponse;

typedef boost::shared_ptr< ::bruce_msgs::PredictSLAMUpdateResponse > PredictSLAMUpdateResponsePtr;
typedef boost::shared_ptr< ::bruce_msgs::PredictSLAMUpdateResponse const> PredictSLAMUpdateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator1> & lhs, const ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.isam2_updates == rhs.isam2_updates &&
    lhs.keyframes == rhs.keyframes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator1> & lhs, const ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bruce_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6410c519772996708be4e4c7d31590ad";
  }

  static const char* value(const ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6410c51977299670ULL;
  static const uint64_t static_value2 = 0x8be4e4c7d31590adULL;
};

template<class ContainerAllocator>
struct DataType< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bruce_msgs/PredictSLAMUpdateResponse";
  }

  static const char* value(const ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bruce_msgs/ISAM2Update[] isam2_updates\n"
"nav_msgs/Path[] keyframes\n"
"\n"
"\n"
"================================================================================\n"
"MSG: bruce_msgs/ISAM2Update\n"
"Header header\n"
"uint32 key\n"
"uint8[] isam2\n"
"uint8[] graph\n"
"uint8[] values\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isam2_updates);
      stream.next(m.keyframes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PredictSLAMUpdateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bruce_msgs::PredictSLAMUpdateResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "isam2_updates: ";
    if (v.isam2_updates.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.isam2_updates.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::bruce_msgs::ISAM2Update_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.isam2_updates[i]);
    }
    if (v.isam2_updates.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "keyframes: ";
    if (v.keyframes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.keyframes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.keyframes[i]);
    }
    if (v.keyframes.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRUCE_MSGS_MESSAGE_PREDICTSLAMUPDATERESPONSE_H
