// Generated by gencpp from file bruce_msgs/PredictSLAMUpdate.msg
// DO NOT EDIT!


#ifndef BRUCE_MSGS_MESSAGE_PREDICTSLAMUPDATE_H
#define BRUCE_MSGS_MESSAGE_PREDICTSLAMUPDATE_H

#include <ros/service_traits.h>


#include <bruce_msgs/PredictSLAMUpdateRequest.h>
#include <bruce_msgs/PredictSLAMUpdateResponse.h>


namespace bruce_msgs
{

struct PredictSLAMUpdate
{

typedef PredictSLAMUpdateRequest Request;
typedef PredictSLAMUpdateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PredictSLAMUpdate
} // namespace bruce_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bruce_msgs::PredictSLAMUpdate > {
  static const char* value()
  {
    return "18a5f92af2249a995192f2aa3a6de24b";
  }

  static const char* value(const ::bruce_msgs::PredictSLAMUpdate&) { return value(); }
};

template<>
struct DataType< ::bruce_msgs::PredictSLAMUpdate > {
  static const char* value()
  {
    return "bruce_msgs/PredictSLAMUpdate";
  }

  static const char* value(const ::bruce_msgs::PredictSLAMUpdate&) { return value(); }
};


// service_traits::MD5Sum< ::bruce_msgs::PredictSLAMUpdateRequest> should match
// service_traits::MD5Sum< ::bruce_msgs::PredictSLAMUpdate >
template<>
struct MD5Sum< ::bruce_msgs::PredictSLAMUpdateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bruce_msgs::PredictSLAMUpdate >::value();
  }
  static const char* value(const ::bruce_msgs::PredictSLAMUpdateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bruce_msgs::PredictSLAMUpdateRequest> should match
// service_traits::DataType< ::bruce_msgs::PredictSLAMUpdate >
template<>
struct DataType< ::bruce_msgs::PredictSLAMUpdateRequest>
{
  static const char* value()
  {
    return DataType< ::bruce_msgs::PredictSLAMUpdate >::value();
  }
  static const char* value(const ::bruce_msgs::PredictSLAMUpdateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bruce_msgs::PredictSLAMUpdateResponse> should match
// service_traits::MD5Sum< ::bruce_msgs::PredictSLAMUpdate >
template<>
struct MD5Sum< ::bruce_msgs::PredictSLAMUpdateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bruce_msgs::PredictSLAMUpdate >::value();
  }
  static const char* value(const ::bruce_msgs::PredictSLAMUpdateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bruce_msgs::PredictSLAMUpdateResponse> should match
// service_traits::DataType< ::bruce_msgs::PredictSLAMUpdate >
template<>
struct DataType< ::bruce_msgs::PredictSLAMUpdateResponse>
{
  static const char* value()
  {
    return DataType< ::bruce_msgs::PredictSLAMUpdate >::value();
  }
  static const char* value(const ::bruce_msgs::PredictSLAMUpdateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BRUCE_MSGS_MESSAGE_PREDICTSLAMUPDATE_H
