// Generated by gencpp from file bruce_msgs/QueryExplorationPathResponse.msg
// DO NOT EDIT!


#ifndef BRUCE_MSGS_MESSAGE_QUERYEXPLORATIONPATHRESPONSE_H
#define BRUCE_MSGS_MESSAGE_QUERYEXPLORATIONPATHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace bruce_msgs
{
template <class ContainerAllocator>
struct QueryExplorationPathResponse_
{
  typedef QueryExplorationPathResponse_<ContainerAllocator> Type;

  QueryExplorationPathResponse_()
    : path()
    , type()  {
    }
  QueryExplorationPathResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , type(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _path_type;
  _path_type path;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QueryExplorationPathResponse_

typedef ::bruce_msgs::QueryExplorationPathResponse_<std::allocator<void> > QueryExplorationPathResponse;

typedef boost::shared_ptr< ::bruce_msgs::QueryExplorationPathResponse > QueryExplorationPathResponsePtr;
typedef boost::shared_ptr< ::bruce_msgs::QueryExplorationPathResponse const> QueryExplorationPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator1> & lhs, const ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator1> & lhs, const ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bruce_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6d0f6f88862321f9f30fe0e54019c85";
  }

  static const char* value(const ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6d0f6f88862321fULL;
  static const uint64_t static_value2 = 0x9f30fe0e54019c85ULL;
};

template<class ContainerAllocator>
struct DataType< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bruce_msgs/QueryExplorationPathResponse";
  }

  static const char* value(const ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"nav_msgs/Path path\n"
"string type\n"
"\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryExplorationPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bruce_msgs::QueryExplorationPathResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "path: ";
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRUCE_MSGS_MESSAGE_QUERYEXPLORATIONPATHRESPONSE_H
