// Generated by gencpp from file bruce_msgs/QueryExplorationPathRequest.msg
// DO NOT EDIT!


#ifndef BRUCE_MSGS_MESSAGE_QUERYEXPLORATIONPATHREQUEST_H
#define BRUCE_MSGS_MESSAGE_QUERYEXPLORATIONPATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bruce_msgs
{
template <class ContainerAllocator>
struct QueryExplorationPathRequest_
{
  typedef QueryExplorationPathRequest_<ContainerAllocator> Type;

  QueryExplorationPathRequest_()
    {
    }
  QueryExplorationPathRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QueryExplorationPathRequest_

typedef ::bruce_msgs::QueryExplorationPathRequest_<std::allocator<void> > QueryExplorationPathRequest;

typedef boost::shared_ptr< ::bruce_msgs::QueryExplorationPathRequest > QueryExplorationPathRequestPtr;
typedef boost::shared_ptr< ::bruce_msgs::QueryExplorationPathRequest const> QueryExplorationPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace bruce_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bruce_msgs/QueryExplorationPathRequest";
  }

  static const char* value(const ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Empty request\n"
"\n"
"\n"
;
  }

  static const char* value(const ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryExplorationPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::bruce_msgs::QueryExplorationPathRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BRUCE_MSGS_MESSAGE_QUERYEXPLORATIONPATHREQUEST_H
