// Generated by gencpp from file bruce_msgs/QueryExplorationPath.msg
// DO NOT EDIT!


#ifndef BRUCE_MSGS_MESSAGE_QUERYEXPLORATIONPATH_H
#define BRUCE_MSGS_MESSAGE_QUERYEXPLORATIONPATH_H

#include <ros/service_traits.h>


#include <bruce_msgs/QueryExplorationPathRequest.h>
#include <bruce_msgs/QueryExplorationPathResponse.h>


namespace bruce_msgs
{

struct QueryExplorationPath
{

typedef QueryExplorationPathRequest Request;
typedef QueryExplorationPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryExplorationPath
} // namespace bruce_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bruce_msgs::QueryExplorationPath > {
  static const char* value()
  {
    return "d6d0f6f88862321f9f30fe0e54019c85";
  }

  static const char* value(const ::bruce_msgs::QueryExplorationPath&) { return value(); }
};

template<>
struct DataType< ::bruce_msgs::QueryExplorationPath > {
  static const char* value()
  {
    return "bruce_msgs/QueryExplorationPath";
  }

  static const char* value(const ::bruce_msgs::QueryExplorationPath&) { return value(); }
};


// service_traits::MD5Sum< ::bruce_msgs::QueryExplorationPathRequest> should match
// service_traits::MD5Sum< ::bruce_msgs::QueryExplorationPath >
template<>
struct MD5Sum< ::bruce_msgs::QueryExplorationPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bruce_msgs::QueryExplorationPath >::value();
  }
  static const char* value(const ::bruce_msgs::QueryExplorationPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bruce_msgs::QueryExplorationPathRequest> should match
// service_traits::DataType< ::bruce_msgs::QueryExplorationPath >
template<>
struct DataType< ::bruce_msgs::QueryExplorationPathRequest>
{
  static const char* value()
  {
    return DataType< ::bruce_msgs::QueryExplorationPath >::value();
  }
  static const char* value(const ::bruce_msgs::QueryExplorationPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bruce_msgs::QueryExplorationPathResponse> should match
// service_traits::MD5Sum< ::bruce_msgs::QueryExplorationPath >
template<>
struct MD5Sum< ::bruce_msgs::QueryExplorationPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bruce_msgs::QueryExplorationPath >::value();
  }
  static const char* value(const ::bruce_msgs::QueryExplorationPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bruce_msgs::QueryExplorationPathResponse> should match
// service_traits::DataType< ::bruce_msgs::QueryExplorationPath >
template<>
struct DataType< ::bruce_msgs::QueryExplorationPathResponse>
{
  static const char* value()
  {
    return DataType< ::bruce_msgs::QueryExplorationPath >::value();
  }
  static const char* value(const ::bruce_msgs::QueryExplorationPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BRUCE_MSGS_MESSAGE_QUERYEXPLORATIONPATH_H
