(cl:in-package rti_dvl-msg)
(cl:export '(CEPO-VAL
          CEPO
          CEAUTOSTART-VAL
          CEAUTOSTART
          CEI-VAL
          CEI
          C485OUT-VAL
          C485OUT
          C232OUT-VAL
          C232OUT
          CBTON-VAL
          CBTON
          CBTBB-VAL
          CBTBB
          CBTMX-VAL
          CBTMX
          CBTBL-VAL
          CBTBL
          CBTT-VAL
          CBTT
          CBTTBP-VAL
          CBTTBP
          CBTST-VAL
          CBTST
          CBTFILT-VAL
          CBTFILT
          CWSSC-VAL
          CWSSC
          CWS-VAL
          CWS
          CWT-VAL
          CWT
          CTD-VAL
          CTD
          CWSS-VAL
          CWSS
          CHO-VAL
          CHO
          CHS-VAL
          CHS
          CTS-VAL
          CTS
          CVSF-VAL
          CVSF
))