// Generated by gencpp from file rti_dvl/BottomTrack.msg
// DO NOT EDIT!


#ifndef RTI_DVL_MESSAGE_BOTTOMTRACK_H
#define RTI_DVL_MESSAGE_BOTTOMTRACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rti_dvl/Command.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace rti_dvl
{
template <class ContainerAllocator>
struct BottomTrack_
{
  typedef BottomTrack_<ContainerAllocator> Type;

  BottomTrack_()
    : header()
    , command()
    , sample(0)
    , time(0.0)
    , velocity()
    , orientation()
    , temperature(0.0)
    , altitude(0.0)
    , pressure(0.0)  {
    }
  BottomTrack_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command(_alloc)
    , sample(0)
    , time(0.0)
    , velocity(_alloc)
    , orientation(_alloc)
    , temperature(0.0)
    , altitude(0.0)
    , pressure(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::rti_dvl::Command_<ContainerAllocator>  _command_type;
  _command_type command;

   typedef uint64_t _sample_type;
  _sample_type sample;

   typedef double _time_type;
  _time_type time;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef double _temperature_type;
  _temperature_type temperature;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _pressure_type;
  _pressure_type pressure;





  typedef boost::shared_ptr< ::rti_dvl::BottomTrack_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rti_dvl::BottomTrack_<ContainerAllocator> const> ConstPtr;

}; // struct BottomTrack_

typedef ::rti_dvl::BottomTrack_<std::allocator<void> > BottomTrack;

typedef boost::shared_ptr< ::rti_dvl::BottomTrack > BottomTrackPtr;
typedef boost::shared_ptr< ::rti_dvl::BottomTrack const> BottomTrackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rti_dvl::BottomTrack_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rti_dvl::BottomTrack_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rti_dvl::BottomTrack_<ContainerAllocator1> & lhs, const ::rti_dvl::BottomTrack_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.command == rhs.command &&
    lhs.sample == rhs.sample &&
    lhs.time == rhs.time &&
    lhs.velocity == rhs.velocity &&
    lhs.orientation == rhs.orientation &&
    lhs.temperature == rhs.temperature &&
    lhs.altitude == rhs.altitude &&
    lhs.pressure == rhs.pressure;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rti_dvl::BottomTrack_<ContainerAllocator1> & lhs, const ::rti_dvl::BottomTrack_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rti_dvl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rti_dvl::BottomTrack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rti_dvl::BottomTrack_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rti_dvl::BottomTrack_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rti_dvl::BottomTrack_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rti_dvl::BottomTrack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rti_dvl::BottomTrack_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rti_dvl::BottomTrack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e236d20adc4e75be05aff82938ad572b";
  }

  static const char* value(const ::rti_dvl::BottomTrack_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe236d20adc4e75beULL;
  static const uint64_t static_value2 = 0x05aff82938ad572bULL;
};

template<class ContainerAllocator>
struct DataType< ::rti_dvl::BottomTrack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rti_dvl/BottomTrack";
  }

  static const char* value(const ::rti_dvl::BottomTrack_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rti_dvl::BottomTrack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"rti_dvl/Command command\n"
"\n"
"# Sample number\n"
"uint64 sample\n"
"# Start time of the sample in second\n"
"float64 time\n"
"# Velocity in m/s in body frame\n"
"geometry_msgs/Vector3 velocity\n"
"# Orientation (roll, pitch, yaw) at the sample\n"
"geometry_msgs/Vector3 orientation\n"
"# Temperature in Celsius\n"
"float64 temperature\n"
"# Depth below transducer in m\n"
"float64 altitude\n"
"# Pressure in BAR\n"
"float64 pressure\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rti_dvl/Command\n"
"# Subsystem Configuration\n"
"# 3: 600 kHz 4 beam 20 degree piston\n"
"string CEPO \n"
"\n"
"# CEAUTOSTART On/OFF\n"
"# 0	OFF\n"
"# 1	DO NOT USE\n"
"# 2	RS232\n"
"# 3	RS485\n"
"# 4	RS422\n"
"# 5	EMAC\n"
"# 6	UDP\n"
"string CEAUTOSTART\n"
"\n"
"# Ensemble output period in HH:MM:SS.hh\n"
"string CEI\n"
"\n"
"# Output format\n"
"# [1] - RoweTech Binary (RTB)\n"
"# [1] - RoweTech DVL (RTD)\n"
"# [2] - ASCII Format\n"
"# [2] - DVL Format\n"
"# [3] - NMEA Status String\n"
"# [4] - Ocean Server NMEA DVL Format\n"
"# [5] - DVL Format\n"
"# [100] - PD0\n"
"# [103] - PD3 Binary Format\n"
"# [104] - PD4 Binary Format\n"
"# [105] - PD5 Binary Format\n"
"# [106] - PD6 ASCII Format\n"
"# [113] - PD13 ASCII Format\n"
"string C485OUT \n"
"string C232OUT \n"
"\n"
"# 1 - Turn ON Bottom Tracking\n"
"# 0 - Turn OFF Bottom Tracking\n"
"string CBTON\n"
"\n"
"# Bottom Track Broadband. Sets Bottom Track coded pulse transmission and lag.\n"
"# n, m, d, x\n"
"# [n] - Transmit Pulse Type and Processing\n"
"#     0 = Narrowband.\n"
"#     Provides long range profiles at the expense of variance.\n"
"#     Not recommended for use with bin size less than the default bin size.\n"
"#     1 = Broadband.\n"
"#     Typically 15% less range than narrow band but has greatly reduced variance (depending on lag length).\n"
"#     Used in conjunction with CWPBP for small bins.\n"
"#     2 = Un-coded Broadband (no ambiguity resolver).\n"
"#     Non-coded has slightly higher variance than the coded transmit without the annoying autocorrelation side peaks. Better for small bins.\n"
"#     4 = Non Coded Broadband pulse-to-pulse (no ambiguity resolver).\n"
"#     Provides ultra low variance for small bin sizes.\n"
"#     7 = Auto Switch (n=0, n=2, n=4)\n"
"# [m] - Lag length in vertical meters (m)\n"
"#     The lag length will set the maximum velocity the ADCP can read. A rule of thumb is to set the lag length, where 1.5 is a 'safety factor'.    \n"
"# [d] - Long Range Narrowband Auto Switch Depth (m)\n"
"#     The depth to switch from Broadband to Narrowband in meters. This is used in the Auto Switch mode.\n"
"# [x] - Beam Multiplex\n"
"#     1 = ping and process each beam one at a time.\n"
"#     2 = ping and process beam pairs.\n"
"#     4 = ping and process all four beams together.\n"
"string CBTBB\n"
"\n"
"# Set the maximum depth to search for the bottom. This will reduce the amount of time in the search algorithm.\n"
"string CBTMX\n"
"\n"
"# Blanking distance for the Bottom Track ping. This is the area that will be ignored just after the ADCP.\n"
"# n.nn, m.mm\n"
"#     [n.nn] - 0 to 10 meters. Sets the vertical distance from the face of the transducer at which the bottom detection algorithm begins searching for the bottom when range to the bottom is LESS than CBTT parameter b.\n"
"#     [m.mm] - 0 to 300 meters. Sets the vertical distance from the face of the transducer at which the bottom detection algorithm begins searching for the bottom when range to the bottom is GREATER than CBTT parameter b.\n"
"string CBTBL\n"
"\n"
"# Bottom Track thresholds.\n"
"# a,b,c,d\n"
"#     [a] - SNR (dB) Shallow Detection Threshold. SNR(dB) shallow detection threshold. Lowering the SNR counts \"a\" and/or \"c\" will allow to the DVL to detect smaller bottom echo at greater range. The consequence is that DVL may false detect the bottom at the wrong range when the bottom signal is weak.\n"
"#     [b] - Depth(m) Shallow Switch. Depth(m) at which the bottom track switches from using the shallow to the deep SNR. Conditions in shallow water (high backscatter) can be different than deep water so \"b\" allows for two different SNR settings one for shallow (\"a\") and one for deep (\"c\").\n"
"#     [c] - SNR(dB) Deep Detection Threshold. SNR(dB) deep detection threshold. Lowering the SNR counts \"a\" and/or \"c\" will allow to the DVL to detect smaller bottom echo at greater range. The consequence is that DVL may false detect the bottom at the wrong range when the bottom signal is weak.\n"
"#     [d] - Depth(m) Deep Switch. Depth(m) at which the bottom track switches from low to high gain receive. The ADCP/DVL has a high power transmitter. In shallow water the bottom echo may saturate the receiver input. While this does not harm the system saturation limits the measurable signal level of the bottom echo which can make it difficult to detect the bottom in a high water backscatter environment. The ADCP/DVL places the receiver in low gain when the depth is below the \"d\" parameter setting. The change in gain is about 40 dB. If you observe the ADCP/DVL having difficulty detecting the bottom near the \"d\" setting you may need set \"d\" to a deeper or more shallow depth depending on the depth where the detection is poor. A good rule to follow is a strong bottom echo requires a larger value in d and a weak bottom echo a smaller value.\n"
"string CBTT\n"
"\n"
"# Not used for bottom tracking only\n"
"# This is used to create a pause between the Water Profile and Bottom Track ping. This will allow the Bottom Track ping to die down if it is reverberating and causing interference in the Water Profile ping.\n"
"string CBTTBP\n"
"\n"
"# Set thresholds to mark the data bad. This will give 3 options of forcing data to be bad. This can also be used to make all the data good by settings all the thresholds to 0.\n"
"# c.cc,q.qq,v.vv\n"
"#     [c.cc] - Correlation threshold.\n"
"#     [q.qq] - Error Velocity threshold. Range: m/s\n"
"#     [v.vv] - Velocity threshold. Range: m/s\n"
"string CBTST\n"
"\n"
"# Low pass filtering helps reduce velocity measurement noise\n"
"# a,b,c,d,e\n"
"# We do not recommend that the filter be enabled.\n"
"string CBTFILT\n"
"\n"
"# Water Speed of Sound Control.\n"
"# 1, 2, 3, 4\n"
"#     [1] - Water Temperature Source\n"
"#     [2] - Transducer Depth Source\n"
"#     [3] - Salinity Source\n"
"#     [4] - Speed of Sound Source\n"
"# Choices\n"
"#     0 = Command\n"
"#     1 = Sensor\n"
"#     2 = Internal Calculation.\n"
"string CWSSC\n"
"\n"
"# Water Salinity (ppt). Used in the water speed of sound calculation\n"
"string CWS\n"
"\n"
"# Water Temperature (degrees celsius). Used in the water speed of sound calculation if the temperature sensor is not available.\n"
"string CWT\n"
"\n"
"# Transducer Depth (meters). Used in the water speed of sound calculation.\n"
"string CTD\n"
"\n"
"# Water Speed of Sound (meters per second).\n"
"string CWSS\n"
"\n"
"# This will set the heading offset for the ADCP. The heading offset will be applied to the heading value before it is to be used within the system for calculations. Typically only the first value is given.\n"
"string CHO\n"
"# Heading source. Used to state whether to use no heading, internal compass heading or GPS heading. This value should be set to GPS HDT if you cannot calibrate the compass in its environment.\n"
"string CHS\n"
"# Tilt Source. Set whether to use the tilt from internal compass or no tilt.\n"
"string CTS\n"
"\n"
"# Velocity Scale Factor\n"
"#  n.nn, m.mm\n"
"#     [n.nn] - Water Velocity Scale Factor\n"
"#     [m.mm] - Bottom Track Scale Factor\n"
"string CVSF\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rti_dvl::BottomTrack_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rti_dvl::BottomTrack_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command);
      stream.next(m.sample);
      stream.next(m.time);
      stream.next(m.velocity);
      stream.next(m.orientation);
      stream.next(m.temperature);
      stream.next(m.altitude);
      stream.next(m.pressure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BottomTrack_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rti_dvl::BottomTrack_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rti_dvl::BottomTrack_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer< ::rti_dvl::Command_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sample: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.sample);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "orientation: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "temperature: ";
    Printer<double>::stream(s, indent + "  ", v.temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pressure: ";
    Printer<double>::stream(s, indent + "  ", v.pressure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RTI_DVL_MESSAGE_BOTTOMTRACK_H
