// Generated by gencpp from file rti_dvl/Command.msg
// DO NOT EDIT!


#ifndef RTI_DVL_MESSAGE_COMMAND_H
#define RTI_DVL_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rti_dvl
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : CEPO()
    , CEAUTOSTART()
    , CEI()
    , C485OUT()
    , C232OUT()
    , CBTON()
    , CBTBB()
    , CBTMX()
    , CBTBL()
    , CBTT()
    , CBTTBP()
    , CBTST()
    , CBTFILT()
    , CWSSC()
    , CWS()
    , CWT()
    , CTD()
    , CWSS()
    , CHO()
    , CHS()
    , CTS()
    , CVSF()  {
    }
  Command_(const ContainerAllocator& _alloc)
    : CEPO(_alloc)
    , CEAUTOSTART(_alloc)
    , CEI(_alloc)
    , C485OUT(_alloc)
    , C232OUT(_alloc)
    , CBTON(_alloc)
    , CBTBB(_alloc)
    , CBTMX(_alloc)
    , CBTBL(_alloc)
    , CBTT(_alloc)
    , CBTTBP(_alloc)
    , CBTST(_alloc)
    , CBTFILT(_alloc)
    , CWSSC(_alloc)
    , CWS(_alloc)
    , CWT(_alloc)
    , CTD(_alloc)
    , CWSS(_alloc)
    , CHO(_alloc)
    , CHS(_alloc)
    , CTS(_alloc)
    , CVSF(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CEPO_type;
  _CEPO_type CEPO;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CEAUTOSTART_type;
  _CEAUTOSTART_type CEAUTOSTART;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CEI_type;
  _CEI_type CEI;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _C485OUT_type;
  _C485OUT_type C485OUT;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _C232OUT_type;
  _C232OUT_type C232OUT;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CBTON_type;
  _CBTON_type CBTON;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CBTBB_type;
  _CBTBB_type CBTBB;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CBTMX_type;
  _CBTMX_type CBTMX;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CBTBL_type;
  _CBTBL_type CBTBL;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CBTT_type;
  _CBTT_type CBTT;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CBTTBP_type;
  _CBTTBP_type CBTTBP;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CBTST_type;
  _CBTST_type CBTST;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CBTFILT_type;
  _CBTFILT_type CBTFILT;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CWSSC_type;
  _CWSSC_type CWSSC;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CWS_type;
  _CWS_type CWS;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CWT_type;
  _CWT_type CWT;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CTD_type;
  _CTD_type CTD;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CWSS_type;
  _CWSS_type CWSS;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CHO_type;
  _CHO_type CHO;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CHS_type;
  _CHS_type CHS;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CTS_type;
  _CTS_type CTS;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _CVSF_type;
  _CVSF_type CVSF;





  typedef boost::shared_ptr< ::rti_dvl::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rti_dvl::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::rti_dvl::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::rti_dvl::Command > CommandPtr;
typedef boost::shared_ptr< ::rti_dvl::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rti_dvl::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rti_dvl::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rti_dvl::Command_<ContainerAllocator1> & lhs, const ::rti_dvl::Command_<ContainerAllocator2> & rhs)
{
  return lhs.CEPO == rhs.CEPO &&
    lhs.CEAUTOSTART == rhs.CEAUTOSTART &&
    lhs.CEI == rhs.CEI &&
    lhs.C485OUT == rhs.C485OUT &&
    lhs.C232OUT == rhs.C232OUT &&
    lhs.CBTON == rhs.CBTON &&
    lhs.CBTBB == rhs.CBTBB &&
    lhs.CBTMX == rhs.CBTMX &&
    lhs.CBTBL == rhs.CBTBL &&
    lhs.CBTT == rhs.CBTT &&
    lhs.CBTTBP == rhs.CBTTBP &&
    lhs.CBTST == rhs.CBTST &&
    lhs.CBTFILT == rhs.CBTFILT &&
    lhs.CWSSC == rhs.CWSSC &&
    lhs.CWS == rhs.CWS &&
    lhs.CWT == rhs.CWT &&
    lhs.CTD == rhs.CTD &&
    lhs.CWSS == rhs.CWSS &&
    lhs.CHO == rhs.CHO &&
    lhs.CHS == rhs.CHS &&
    lhs.CTS == rhs.CTS &&
    lhs.CVSF == rhs.CVSF;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rti_dvl::Command_<ContainerAllocator1> & lhs, const ::rti_dvl::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rti_dvl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rti_dvl::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rti_dvl::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rti_dvl::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rti_dvl::Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rti_dvl::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rti_dvl::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rti_dvl::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4a778ac84916e4541ed9df1cd1fc61c";
  }

  static const char* value(const ::rti_dvl::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4a778ac84916e45ULL;
  static const uint64_t static_value2 = 0x41ed9df1cd1fc61cULL;
};

template<class ContainerAllocator>
struct DataType< ::rti_dvl::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rti_dvl/Command";
  }

  static const char* value(const ::rti_dvl::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rti_dvl::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Subsystem Configuration\n"
"# 3: 600 kHz 4 beam 20 degree piston\n"
"string CEPO \n"
"\n"
"# CEAUTOSTART On/OFF\n"
"# 0	OFF\n"
"# 1	DO NOT USE\n"
"# 2	RS232\n"
"# 3	RS485\n"
"# 4	RS422\n"
"# 5	EMAC\n"
"# 6	UDP\n"
"string CEAUTOSTART\n"
"\n"
"# Ensemble output period in HH:MM:SS.hh\n"
"string CEI\n"
"\n"
"# Output format\n"
"# [1] - RoweTech Binary (RTB)\n"
"# [1] - RoweTech DVL (RTD)\n"
"# [2] - ASCII Format\n"
"# [2] - DVL Format\n"
"# [3] - NMEA Status String\n"
"# [4] - Ocean Server NMEA DVL Format\n"
"# [5] - DVL Format\n"
"# [100] - PD0\n"
"# [103] - PD3 Binary Format\n"
"# [104] - PD4 Binary Format\n"
"# [105] - PD5 Binary Format\n"
"# [106] - PD6 ASCII Format\n"
"# [113] - PD13 ASCII Format\n"
"string C485OUT \n"
"string C232OUT \n"
"\n"
"# 1 - Turn ON Bottom Tracking\n"
"# 0 - Turn OFF Bottom Tracking\n"
"string CBTON\n"
"\n"
"# Bottom Track Broadband. Sets Bottom Track coded pulse transmission and lag.\n"
"# n, m, d, x\n"
"# [n] - Transmit Pulse Type and Processing\n"
"#     0 = Narrowband.\n"
"#     Provides long range profiles at the expense of variance.\n"
"#     Not recommended for use with bin size less than the default bin size.\n"
"#     1 = Broadband.\n"
"#     Typically 15% less range than narrow band but has greatly reduced variance (depending on lag length).\n"
"#     Used in conjunction with CWPBP for small bins.\n"
"#     2 = Un-coded Broadband (no ambiguity resolver).\n"
"#     Non-coded has slightly higher variance than the coded transmit without the annoying autocorrelation side peaks. Better for small bins.\n"
"#     4 = Non Coded Broadband pulse-to-pulse (no ambiguity resolver).\n"
"#     Provides ultra low variance for small bin sizes.\n"
"#     7 = Auto Switch (n=0, n=2, n=4)\n"
"# [m] - Lag length in vertical meters (m)\n"
"#     The lag length will set the maximum velocity the ADCP can read. A rule of thumb is to set the lag length, where 1.5 is a 'safety factor'.    \n"
"# [d] - Long Range Narrowband Auto Switch Depth (m)\n"
"#     The depth to switch from Broadband to Narrowband in meters. This is used in the Auto Switch mode.\n"
"# [x] - Beam Multiplex\n"
"#     1 = ping and process each beam one at a time.\n"
"#     2 = ping and process beam pairs.\n"
"#     4 = ping and process all four beams together.\n"
"string CBTBB\n"
"\n"
"# Set the maximum depth to search for the bottom. This will reduce the amount of time in the search algorithm.\n"
"string CBTMX\n"
"\n"
"# Blanking distance for the Bottom Track ping. This is the area that will be ignored just after the ADCP.\n"
"# n.nn, m.mm\n"
"#     [n.nn] - 0 to 10 meters. Sets the vertical distance from the face of the transducer at which the bottom detection algorithm begins searching for the bottom when range to the bottom is LESS than CBTT parameter b.\n"
"#     [m.mm] - 0 to 300 meters. Sets the vertical distance from the face of the transducer at which the bottom detection algorithm begins searching for the bottom when range to the bottom is GREATER than CBTT parameter b.\n"
"string CBTBL\n"
"\n"
"# Bottom Track thresholds.\n"
"# a,b,c,d\n"
"#     [a] - SNR (dB) Shallow Detection Threshold. SNR(dB) shallow detection threshold. Lowering the SNR counts \"a\" and/or \"c\" will allow to the DVL to detect smaller bottom echo at greater range. The consequence is that DVL may false detect the bottom at the wrong range when the bottom signal is weak.\n"
"#     [b] - Depth(m) Shallow Switch. Depth(m) at which the bottom track switches from using the shallow to the deep SNR. Conditions in shallow water (high backscatter) can be different than deep water so \"b\" allows for two different SNR settings one for shallow (\"a\") and one for deep (\"c\").\n"
"#     [c] - SNR(dB) Deep Detection Threshold. SNR(dB) deep detection threshold. Lowering the SNR counts \"a\" and/or \"c\" will allow to the DVL to detect smaller bottom echo at greater range. The consequence is that DVL may false detect the bottom at the wrong range when the bottom signal is weak.\n"
"#     [d] - Depth(m) Deep Switch. Depth(m) at which the bottom track switches from low to high gain receive. The ADCP/DVL has a high power transmitter. In shallow water the bottom echo may saturate the receiver input. While this does not harm the system saturation limits the measurable signal level of the bottom echo which can make it difficult to detect the bottom in a high water backscatter environment. The ADCP/DVL places the receiver in low gain when the depth is below the \"d\" parameter setting. The change in gain is about 40 dB. If you observe the ADCP/DVL having difficulty detecting the bottom near the \"d\" setting you may need set \"d\" to a deeper or more shallow depth depending on the depth where the detection is poor. A good rule to follow is a strong bottom echo requires a larger value in d and a weak bottom echo a smaller value.\n"
"string CBTT\n"
"\n"
"# Not used for bottom tracking only\n"
"# This is used to create a pause between the Water Profile and Bottom Track ping. This will allow the Bottom Track ping to die down if it is reverberating and causing interference in the Water Profile ping.\n"
"string CBTTBP\n"
"\n"
"# Set thresholds to mark the data bad. This will give 3 options of forcing data to be bad. This can also be used to make all the data good by settings all the thresholds to 0.\n"
"# c.cc,q.qq,v.vv\n"
"#     [c.cc] - Correlation threshold.\n"
"#     [q.qq] - Error Velocity threshold. Range: m/s\n"
"#     [v.vv] - Velocity threshold. Range: m/s\n"
"string CBTST\n"
"\n"
"# Low pass filtering helps reduce velocity measurement noise\n"
"# a,b,c,d,e\n"
"# We do not recommend that the filter be enabled.\n"
"string CBTFILT\n"
"\n"
"# Water Speed of Sound Control.\n"
"# 1, 2, 3, 4\n"
"#     [1] - Water Temperature Source\n"
"#     [2] - Transducer Depth Source\n"
"#     [3] - Salinity Source\n"
"#     [4] - Speed of Sound Source\n"
"# Choices\n"
"#     0 = Command\n"
"#     1 = Sensor\n"
"#     2 = Internal Calculation.\n"
"string CWSSC\n"
"\n"
"# Water Salinity (ppt). Used in the water speed of sound calculation\n"
"string CWS\n"
"\n"
"# Water Temperature (degrees celsius). Used in the water speed of sound calculation if the temperature sensor is not available.\n"
"string CWT\n"
"\n"
"# Transducer Depth (meters). Used in the water speed of sound calculation.\n"
"string CTD\n"
"\n"
"# Water Speed of Sound (meters per second).\n"
"string CWSS\n"
"\n"
"# This will set the heading offset for the ADCP. The heading offset will be applied to the heading value before it is to be used within the system for calculations. Typically only the first value is given.\n"
"string CHO\n"
"# Heading source. Used to state whether to use no heading, internal compass heading or GPS heading. This value should be set to GPS HDT if you cannot calibrate the compass in its environment.\n"
"string CHS\n"
"# Tilt Source. Set whether to use the tilt from internal compass or no tilt.\n"
"string CTS\n"
"\n"
"# Velocity Scale Factor\n"
"#  n.nn, m.mm\n"
"#     [n.nn] - Water Velocity Scale Factor\n"
"#     [m.mm] - Bottom Track Scale Factor\n"
"string CVSF\n"
;
  }

  static const char* value(const ::rti_dvl::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rti_dvl::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.CEPO);
      stream.next(m.CEAUTOSTART);
      stream.next(m.CEI);
      stream.next(m.C485OUT);
      stream.next(m.C232OUT);
      stream.next(m.CBTON);
      stream.next(m.CBTBB);
      stream.next(m.CBTMX);
      stream.next(m.CBTBL);
      stream.next(m.CBTT);
      stream.next(m.CBTTBP);
      stream.next(m.CBTST);
      stream.next(m.CBTFILT);
      stream.next(m.CWSSC);
      stream.next(m.CWS);
      stream.next(m.CWT);
      stream.next(m.CTD);
      stream.next(m.CWSS);
      stream.next(m.CHO);
      stream.next(m.CHS);
      stream.next(m.CTS);
      stream.next(m.CVSF);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rti_dvl::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rti_dvl::Command_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "CEPO: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CEPO);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CEAUTOSTART: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CEAUTOSTART);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CEI: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CEI);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "C485OUT: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.C485OUT);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "C232OUT: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.C232OUT);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CBTON: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CBTON);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CBTBB: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CBTBB);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CBTMX: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CBTMX);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CBTBL: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CBTBL);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CBTT: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CBTT);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CBTTBP: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CBTTBP);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CBTST: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CBTST);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CBTFILT: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CBTFILT);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CWSSC: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CWSSC);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CWS: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CWS);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CWT: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CWT);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CTD: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CTD);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CWSS: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CWSS);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CHO: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CHO);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CHS: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CHS);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CTS: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CTS);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CVSF: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.CVSF);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RTI_DVL_MESSAGE_COMMAND_H
