// Generated by gencpp from file rti_dvl/DVL.msg
// DO NOT EDIT!


#ifndef RTI_DVL_MESSAGE_DVL_H
#define RTI_DVL_MESSAGE_DVL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace rti_dvl
{
template <class ContainerAllocator>
struct DVL_
{
  typedef DVL_<ContainerAllocator> Type;

  DVL_()
    : header()
    , velocity()
    , temperature(0.0)
    , altitude(0.0)
    , time(0.0)  {
    }
  DVL_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , velocity(_alloc)
    , temperature(0.0)
    , altitude(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef double _temperature_type;
  _temperature_type temperature;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::rti_dvl::DVL_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rti_dvl::DVL_<ContainerAllocator> const> ConstPtr;

}; // struct DVL_

typedef ::rti_dvl::DVL_<std::allocator<void> > DVL;

typedef boost::shared_ptr< ::rti_dvl::DVL > DVLPtr;
typedef boost::shared_ptr< ::rti_dvl::DVL const> DVLConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rti_dvl::DVL_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rti_dvl::DVL_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rti_dvl::DVL_<ContainerAllocator1> & lhs, const ::rti_dvl::DVL_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.velocity == rhs.velocity &&
    lhs.temperature == rhs.temperature &&
    lhs.altitude == rhs.altitude &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rti_dvl::DVL_<ContainerAllocator1> & lhs, const ::rti_dvl::DVL_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rti_dvl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rti_dvl::DVL_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rti_dvl::DVL_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rti_dvl::DVL_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rti_dvl::DVL_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rti_dvl::DVL_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rti_dvl::DVL_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rti_dvl::DVL_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84fe0dd3f2fa07f272dbadf697440637";
  }

  static const char* value(const ::rti_dvl::DVL_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84fe0dd3f2fa07f2ULL;
  static const uint64_t static_value2 = 0x72dbadf697440637ULL;
};

template<class ContainerAllocator>
struct DataType< ::rti_dvl::DVL_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rti_dvl/DVL";
  }

  static const char* value(const ::rti_dvl::DVL_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rti_dvl::DVL_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"geometry_msgs/Vector3 velocity\n"
"float64 temperature\n"
"float64 altitude\n"
"float64 time\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rti_dvl::DVL_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rti_dvl::DVL_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.velocity);
      stream.next(m.temperature);
      stream.next(m.altitude);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DVL_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rti_dvl::DVL_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rti_dvl::DVL_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "temperature: ";
    Printer<double>::stream(s, indent + "  ", v.temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RTI_DVL_MESSAGE_DVL_H
