// Generated by gencpp from file kvh_gyro/gyro.msg
// DO NOT EDIT!


#ifndef KVH_GYRO_MESSAGE_GYRO_H
#define KVH_GYRO_MESSAGE_GYRO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kvh_gyro
{
template <class ContainerAllocator>
struct gyro_
{
  typedef gyro_<ContainerAllocator> Type;

  gyro_()
    : header()
    , status(false)
    , delta()  {
    }
  gyro_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(false)
    , delta(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _status_type;
  _status_type status;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _delta_type;
  _delta_type delta;





  typedef boost::shared_ptr< ::kvh_gyro::gyro_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kvh_gyro::gyro_<ContainerAllocator> const> ConstPtr;

}; // struct gyro_

typedef ::kvh_gyro::gyro_<std::allocator<void> > gyro;

typedef boost::shared_ptr< ::kvh_gyro::gyro > gyroPtr;
typedef boost::shared_ptr< ::kvh_gyro::gyro const> gyroConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kvh_gyro::gyro_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kvh_gyro::gyro_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kvh_gyro::gyro_<ContainerAllocator1> & lhs, const ::kvh_gyro::gyro_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status &&
    lhs.delta == rhs.delta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kvh_gyro::gyro_<ContainerAllocator1> & lhs, const ::kvh_gyro::gyro_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kvh_gyro

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kvh_gyro::gyro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kvh_gyro::gyro_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kvh_gyro::gyro_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kvh_gyro::gyro_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kvh_gyro::gyro_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kvh_gyro::gyro_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kvh_gyro::gyro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7bf4a7f82fe96d9124091847a68d6212";
  }

  static const char* value(const ::kvh_gyro::gyro_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7bf4a7f82fe96d91ULL;
  static const uint64_t static_value2 = 0x24091847a68d6212ULL;
};

template<class ContainerAllocator>
struct DataType< ::kvh_gyro::gyro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kvh_gyro/gyro";
  }

  static const char* value(const ::kvh_gyro::gyro_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kvh_gyro::gyro_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool status #was there an error with the gyro?\n"
"float64[] delta #an array for dx, dy, dz\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kvh_gyro::gyro_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kvh_gyro::gyro_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.delta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gyro_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kvh_gyro::gyro_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kvh_gyro::gyro_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "delta: ";
    if (v.delta.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.delta.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.delta[i]);
    }
    if (v.delta.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // KVH_GYRO_MESSAGE_GYRO_H
