(cl:defpackage bruce_msgs-srv
  (:use )
  (:export
   "GETOCCUPANCYMAP"
   "<GETOCCUPANCYMAP-REQUEST>"
   "GETOCCUPANCYMAP-REQUEST"
   "<GETOCCUPANCYMAP-RESPONSE>"
   "GETOCCUPANCYMAP-RESPONSE"
   "PREDICTSLAMUPDATE"
   "<PREDICTSLAMUPDATE-REQUEST>"
   "PREDICTSLAMUPDATE-REQUEST"
   "<PREDICTSLAMUPDATE-RESPONSE>"
   "PREDICTSLAMUPDATE-RESPONSE"
   "QUERYEXPLORATIONPATH"
   "<QUERYEXPLORATIONPATH-REQUEST>"
   "QUERYEXPLORATIONPATH-REQUEST"
   "<QUERYEXPLORATIONPATH-RESPONSE>"
   "QUERYEXPLORATIONPATH-RESPONSE"
  ))

